### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by Cuddles67** [andro2157/DiscordTokenProtector#27] opened 2022-03-08 04:50 UTC
logs 22:15:34.383 [ERROR] Failed to load config : invalid JSON. [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
22:15:34.384 [WARNING] Using default config!
22:17:08.635 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.702 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.850 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.901 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:08.951 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.001 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.151 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.201 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.251 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.301 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.351 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.401 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.451 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.501 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.550 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.601 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.651 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.702 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.801 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.850 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:09.951 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.002 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.102 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.151 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.201 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.250 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.301 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.351 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.400 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.451 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.501 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.550 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.600 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.650 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.701 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.801 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.851 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:10.951 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.002 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.052 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.150 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.201 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.251 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.301 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.351 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.401 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.451 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.500 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.550 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.600 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.650 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.700 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.851 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:11.950 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.001 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.049 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.100 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.151 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.201 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.251 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.300 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.351 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.401 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.451 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.500 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.550 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.601 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.650 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.700 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.850 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:12.950 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.000 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.150 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.200 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.250 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.301 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.350 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.400 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.450 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.501 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.550 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.600 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.650 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.700 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.850 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:13.951 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.001 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.149 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.200 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.250 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.535 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:14.817 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:15.100 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:15.383 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:15.667 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:15.950 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:16.233 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:16.516 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:16.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:17.084 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:17.386 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:17.686 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:18.004 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:18.321 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:18.617 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:18.901 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:19.184 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:19.467 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:19.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:20.034 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:20.317 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:20.601 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:20.889 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:21.185 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:21.470 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:21.751 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:22.034 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:22.317 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:22.600 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:22.887 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:23.169 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:23.467 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:23.770 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:24.087 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:24.418 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:24.701 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:24.983 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:25.267 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:25.554 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:25.854 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:26.152 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:26.455 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:26.754 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:27.051 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:27.333 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:27.616 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:27.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.184 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.468 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.850 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:28.950 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.001 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.149 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.202 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.250 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.300 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.350 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.401 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.450 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.500 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.549 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.601 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.650 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.699 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.750 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.800 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.851 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.900 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:29.950 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.001 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.050 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.101 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.151 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.200 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.251 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.300 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.927 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:30.983 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.033 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.084 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.135 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.184 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.235 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.284 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.335 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.383 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.434 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.483 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.534 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.584 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.634 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.684 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.733 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.783 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.834 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.884 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.933 [WARNING] Unable to get the secure encryption type : the file is too short.
22:17:31.983 [WARNING] Unable to get the secure encryption type : the file is too short.

**Comment by andro2157** [comment] 2022-03-08 18:47
Duplicate of #25

**Closed by andro2157** 2022-03-08 18:47 UTC
