### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jigsaw88** [andro2157/DiscordTokenProtector#33] opened 2022-03-25 23:52 UTC
Suggestions:
- Adding the option to hide it to the system tray
- Make 3 Different "Profiles" or the option to use it for Normal DC, DC Canary & PTB at the same time.

**Comment by andro2157** [comment] 2022-03-28 18:38
Hello,
If you close DTP, it'll automatically hide in the system tray.
For the other Discord builds, I'll try to look into it (Duplicate of #26)

**Closed by andro2157** 2022-03-28 18:38 UTC
